### PR TITLE
Adding an artifact for checking module archive deployment in ESB

### PR DESCRIPTION
**Pull request by kavithasub**
This PR is creating for updated read-me with mar file content artifact.

### CODE REVIEW

**Comment by chamaraanu** [comment]
Reviewing in progress.

**Comment by chamaraanu** [comment]
Please create the folder structure as; 
products/wso2_ESB/modules/

and add your module as service_operator_counter/ and then add the artefact and README in there. 

This convention will help us to add more modules in different functionalities in a nicely arranged folder structure.

**Comment by kavithasub** [comment]
Same artifacts are moved to newly created folder.

**Comment by chamaraanu** [comment]
Tested and verified.

**Pull request merged**
