### PR TITLE
WSO2 APIM CR 1.10 Release(Up to Release_6)

### PR DESCRIPTION
**Pull request by sithijaharith**
WSO2 APIM CR 1.10 Release(Up to Release_6)

### CODE REVIEW

**Comment by nu1silva** [comment]
Why is it up to Release_6? What about 7 and 8?

**Comment by sithijaharith** [comment]
APIM release 1.10 and 1.9.1 we have 2 separate projects.So Usually we are
maintain only 1.9.1 project to commit new scripts after scripted in release
6.

**Comment by nu1silva** [comment]
1.9.1 is released and 1.10.0 is also released. But, as you can understand we need to maintain both these branches. Once a new feature is added to the 1.10.0 release these should be automated on top of what was done for 1.9.1 (new feature might be a CR for Virtusa).

So, IMHO we need to maintain both 1.9.1 and 1.10.0 synced with the changes. If there are any issues (on maintenance) with this procedure please let me know.

**Comment by sithijaharith** [comment]
When we provide CR's of user creation in 1.10 we have committed  release 6
also as requested by evanthika.Hovever we have some maintenance effort for
updating both 1.9.1 and 1.10. I'll discuss with gihan and let you tommorow
morning regarding this  ,because im out of office right now.

**Comment by nu1silva** [comment]
Yes please. Thanks.

**Pull request closed without merging**
