### PR TITLE
Artifacts for 'Message Filtering' user story

### PR DESCRIPTION
**Pull request by sashikamw**
Artifacts for 'Message Filtering' user story

### CODE REVIEW

**Review by ushanib — COMMENTED** [review]
Hi Shashika,

Please remove ~ files.
E.g.,
/MessageRouting/MessageFiltering/Endpoints/StockEndpoint.bal~

**Review by ushanib — CHANGES_REQUESTED** [review]
Please remove ~ files.

/MessageRouting/MessageFiltering/Endpoints/StockEndpoint.bal~

**Comment by sashikamw** [comment]
"/MessageRouting/MessageFiltering/Endpoints/StockEndpoint.bal~" tmp file has been removed in the latest commit

**Review by ushanib — APPROVED** [review]

**Review by ushanib — CHANGES_REQUESTED** [review]
Hi Sashika, 
Please mention the Ballerina version in the readme which we can run these samples since it can change frequently. 

Thanks

**Comment by sashikamw** [comment]
Requested changes are updated in the "https://github.com/wso2/wso2-qa-artifacts/pull/116". Hence closing this pull request

**Pull request closed without merging**
