### PR TITLE
CEP Agregate functions and ML flow

### PR DESCRIPTION
**Pull request by sashikamw**

### CODE REVIEW

**Comment by nu1silva** [comment]
assigned Shavantha(CEP) and Asanka(ML) to review and merge

**Comment by shavantha** [comment]
Hi sashika
I checked the ML flow artifacts and have the following two points
1. I think we should update the ReadMe with the steps that ML extension should be installed. we can point to the p2 given on https://docs.wso2.com/display/CEP400/Installing+Machine+Learner+Features

2.After installing the features as on the link above I updated the file path of ml file to my location as below but the file path was not identified

from InputStream#ml:predict('file:///home/shavantha/products/cep/ml_integration/MLFlow/downloaded-ml-model', 'double')
select *
insert into PredictionStream1;

I see the below error, so I tried giving the path as : registry:/_system/governance/mlmodels/ ibut still no luck. Is this the file required 

org.wso2.carbon.event.processor.core.exception.ExecutionPlanConfigurationException: org.wso2.carbon.event.processor.core.exception.ExecutionPlanConfigurationException: org.wso2.siddhi.core.exception.ExecutionPlanCreationException: Error while retrieving ML-model : file:///home/shavantha/products/cep/ml_integration/MLFlow/downloaded-ml-model

**Comment by sashikamw** [comment]
Thanks for pointing this out. I will update the readme file with steps to install ML features in CEP.

When providing the path to the ML model we can refer it from the file system or through the registry. This issue could be due to the 'downloaded-ml-model', I found out that this model was updated recently. And with the updated model this works fine. I will update the artifacts with latest ml model.

**Comment by shavantha** [comment]
hi sashika

for the AggregateFunctions.jmx better to parameterize the IP and the host instead of giving a fixed ip which users have to change prior to run

regards,shavantha

**Pull request closed without merging**
